name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List disks
        run: sudo fdisk -l && sudo lsblk

      - name: ext4 unencrypted installation
        run: $GITHUB_WORKSPACE/airootfs/usr/local/bin/unattended-install \
          -h
