name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List disks
        run: sudo lsblk && ls -l /dev/disk/by-path
      
      - name: Test connection
        run: nslookup 8.8.8.8

      - name: ext4 unencrypted installation
        run: sudo $GITHUB_WORKSPACE/airootfs/usr/local/bin/unattended-install \
          /dev/disk/by-path/acpi-VMBUS:01-vmbus-00000000000188990000000000000000-lun-0
